# Generated by Django 5.2.3 on 2025-08-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default='No constraints specified'),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(default='Input description not provided'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(default='Output description not provided'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(default='No sample input'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(default='No sample output'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
